name: xhistogram-test
dependencies:
  - python=3.6
  - xarray
  - netcdf4
  - numpy>=1.16
  - pytest
  - numpydoc
  - sphinx
  - ipython
  - matplotlib
  - jupyter_client
  - ipykernel
  - pip
  - pip:
    - nbsphinx
    - docrep
