name: xhistogram
dependencies:
  - python=3.6
  - xarray
  - numpy>=1.16
  - pytest
  - numpydoc
  - sphinx
  - ipython
  - matplotlib
  - jupyter_client
  - ipykernel
  - nbsphinx
  - pip
  - pip:
    - docrep
