name: xhistogram_doc_env
dependencies:
  - python=3.6
  - xarray
  - netcdf4
  - numpy>=1.16
  - pytest
  - numpydoc
  - sphinx
  - ipython
  - matplotlib
  - jupyter_client
  - ipykernel
  - pandoc
  - pip
  - pip:
    - doc8
    - nbsphinx
    - sphinx_rtd_theme
